echo f | xcopy /f /y Apples\build\libs run
echo f | xcopy /f /y Armor\build\libs run
echo f | xcopy /f /y Blocks\build\libs run
echo f | xcopy /f /y CarbonPaper\build\libs run
echo f | xcopy /f /y HorseFood\build\libs run
echo f | xcopy /f /y Macros\build\libs run
echo f | xcopy /f /y MobChanges\build\libs run
echo f | xcopy /f /y Nature\build\libs run
echo f | xcopy /f /y Recipes\build\libs run
echo f | xcopy /f /y Screentext\build\libs run
echo f | xcopy /f /y Spells\build\libs run
echo f | xcopy /f /y Stacks\build\libs run